.TH "md__r_e_a_d_m_e" 3 "Mon Feb 13 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Bacal_Dominik_2 
.PP

.SH "1\&. Utwórz repozytorium w serwisie github o nazwie 'nazwisko_imie'"
.PP
(bez polskich znaków)\&.
.PP
.IP "2." 4
Repozytorium w chwili utworzenia ma zawierać plik licencji oraz README\&.md z krótkim opisem projektu (np\&. Projekt zaliczeniowy na potrzeby przedmiotu Zarządzanie przedsięwzięciami informatycznymi, jakieś punkty, itp\&.)\&.
.IP "3." 4
Zapisać zmiany w repozytorium, nadać etykietę 'init'\&.
.IP "4." 4
Dodać dwa pliki z rozszerzeniem *\&.h i dwa pliki z rozszerzeniem *\&.cpp zawierającymi deklaracje i definicje klas '\fBSequence\fP' i '\fBStatistics\fP'\&. Klasy muszą zawierać: konstruktor domyślny, konstruktor kopiujący, destruktor, funkcje dostępu do składowych, funkcje obliczeniowe\&. Wprowadzić zmiany do repozytorium i nadać im etykietę 'class'\&.
.IP "5." 4
Napisać dokumentację do klas\&. W dokumentacji funkcji muszą pojawić się skomplikowane wzory matematyczne (np\&. całki, sumy, itp\&.), tabele i obrazki/wykresy\&. Można wykorzystać różnego rodzaju wzory na szeregi, gęstości rozkładów prawdopodobieństwa, itp\&. Dodać plik konfiguracyjny programu doxygen\&. Wprowadzić zmiany do repozytorium i nadać im etykietę 'documentation'\&.
.IP "6." 4
Dodać dokumentację w formie dodatkowych stron i zmodyfikowanej strony głównej\&. Wprowadzić zmiany do repozytorium i nadać im etykietę 'doxpage'\&.
.IP "7." 4
Utworzyć nową gałąź 'hotfix' i wprowadzić do niej deklarację i definicję klasy 'ErrorHandle'\&.
.PP
.PP
.PP
 
